[![Made by Mr.Sahraoui](https://img.shields.io/badge/Made%20by-Mr.Sahraoui-orange)](https://digitalpro.dev)
![NLP](https://img.shields.io/badge/NLP-TP%20%202-orange)

<table style="width: 100%;">
<tr>
<td style="width: 50%; text-align: right; vertical-align: middle;">
<img src="https://github.com/gitpizzanow/dummy-files/blob/main/tp1nlp.jpg?raw=true" width="150">
</td>
<td style="width: 50%; text-align: left; vertical-align: middle;">

##  (NLP)   | Text Manipulation &Fake News Classification
> [SERIE](https://tp1-nlp-ing4.netlify.app/)


* *Text cleaning*
* *Text normalization*
* *Text tokenization*


> [DATA](https://www.kaggle.com/datasets/emineyetm/fake-news-detection-datasets)

</td>
</tr>
</table>

In [19]:
!pip install spacy

Requirement already satisfied: spacy in c:\users\pc\anaconda3\lib\site-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (0.24.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (2.10.3)
Requirement already satisfied: jinja2 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\users\pc\anaconda3\lib\site-packages (from spacy) (72.1.0)
Requirement already satisfied: packaging>=20.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (24.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\pc\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\pc\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\pc\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\pc\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pc\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pc\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pc\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.10.5)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\pc\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\pc\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: colorama in c:\users\pc\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: typer>=0.24.0 in c:\users\pc\anaconda3\lib\site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\pc\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\pc\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.1)
Requirement already satisfied: wrapt in c:\users\pc\anaconda3\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (1.17.0)
Requirement already satisfied: click>=8.2.1 in c:\users\pc\anaconda3\lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\pc\anaconda3\lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.0)
Requirement already satisfied: rich>=12.3.0 in c:\users\pc\anaconda3\lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\pc\anaconda3\lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\pc\anaconda3\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\pc\anaconda3\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\pc\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\pc\anaconda3\lib\site-packages (from jinja2->spacy) (3.0.2)

In [20]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     - -------------------------------------- 0.5/12.8 MB 1.6 MB/s eta 0:00:08
     - -------------------------------------- 0.5/12.8 MB 1.6 MB/s eta 0:00:08
     -- ------------------------------------ 0.8/12.8 MB 937.0 kB/s eta 0:00:13
     -- ------------------------------------ 0.8/12.8 MB 937.0 kB/s eta 0:00:13
     --- ----------------------------------- 1.0/12.8 MB 886.5 kB/s eta 0:00:14
     --- ----------------------------------- 1.3/12.8 MB 869.2 kB/s eta 0:00:14
     --- ----------------------------------- 1.3/12.8 MB 869.2 kB/s eta 0:00:14
     ---- ---------------------------------- 1.6/12.8 MB 867.2 kB/s eta 0:00:13
     ---- ---------------------------------- 1.6/12.8 MB 867.2 kB/s eta 0:00:13
     ----- --------------------------------- 1.8/12.8 MB 807.4 kB/s eta 0:00:14
     ----- --------------------------------- 1.8/12.8 MB 807.4 kB/s eta 0:00:14
     ----- --------------------------------- 1.8/12.8 MB 807.4 kB/s eta 0:00:14
     ----- --------------------------------- 1.8/12.8 MB 807.4 kB/s eta 0:00:14
     ------ -------------------------------- 2.1/12.8 MB 662.6 kB/s eta 0:00:17
     ------ -------------------------------- 2.1/12.8 MB 662.6 kB/s eta 0:00:17
     ------- ------------------------------- 2.4/12.8 MB 658.4 kB/s eta 0:00:16
     ------- ------------------------------- 2.4/12.8 MB 658.4 kB/s eta 0:00:16
     ------- ------------------------------- 2.4/12.8 MB 658.4 kB/s eta 0:00:16
     ------- ------------------------------- 2.6/12.8 MB 609.1 kB/s eta 0:00:17
     -------- ------------------------------ 2.9/12.8 MB 633.4 kB/s eta 0:00:16
     -------- ------------------------------ 2.9/12.8 MB 633.4 kB/s eta 0:00:16
     -------- ------------------------------ 2.9/12.8 MB 633.4 kB/s eta 0:00:16
     --------- ----------------------------- 3.1/12.8 MB 626.7 kB/s eta 0:00:16
     --------- ----------------------------- 3.1/12.8 MB 626.7 kB/s eta 0:00:16
     ---------- ---------------------------- 3.4/12.8 MB 625.4 kB/s eta 0:00:16
     ----------- --------------------------- 3.7/12.8 MB 629.4 kB/s eta 0:00:15
     ----------- --------------------------- 3.7/12.8 MB 629.4 kB/s eta 0:00:15
     ----------- --------------------------- 3.7/12.8 MB 629.4 kB/s eta 0:00:15
     ----------- --------------------------- 3.9/12.8 MB 621.5 kB/s eta 0:00:15
     ----------- --------------------------- 3.9/12.8 MB 621.5 kB/s eta 0:00:15
     ----------- --------------------------- 3.9/12.8 MB 621.5 kB/s eta 0:00:15
     ------------ -------------------------- 4.2/12.8 MB 600.3 kB/s eta 0:00:15
     ------------ -------------------------- 4.2/12.8 MB 600.3 kB/s eta 0:00:15
     ------------ -------------------------- 4.2/12.8 MB 600.3 kB/s eta 0:00:15
     ------------ -------------------------- 4.2/12.8 MB 600.3 kB/s eta 0:00:15
     ------------ -------------------------- 4.2/12.8 MB 600.3 kB/s eta 0:00:15
     ------------- ------------------------- 4.5/12.8 MB 555.8 kB/s eta 0:00:16
     ------------- ------------------------- 4.5/12.8 MB 555.8 kB/s eta 0:00:16
     ------------- ------------------------- 4.5/12.8 MB 555.8 kB/s eta 0:00:16
     -------------- ------------------------ 4.7/12.8 MB 538.4 kB/s eta 0:00:16
     -------------- ------------------------ 4.7/12.8 MB 538.4 kB/s eta 0:00:16
     -------------- ------------------------ 4.7/12.8 MB 538.4 kB/s eta 0:00:16
     --------------- ----------------------- 5.0/12.8 MB 524.9 kB/s eta 0:00:15
     --------------- ----------------------- 5.0/12.8 MB 524.9 kB/s eta 0:00:15
     --------------- ----------------------- 5.0/12.8 MB 524.9 kB/s eta 0:00:15
     --------------- ----------------------- 5.2/12.8 MB 516.3 kB/s eta 0:00:15
     --------------- ----------------------- 5.2/12.8 MB 516.3 kB/s eta 0:00:15
     --------------- ----------------------- 5.2/12.8 MB 516.3 kB/s eta 0:00:15
     ---------------- ---------------------- 5.5/12.8 MB 511.7 kB/s eta 0:00:15
     ---------------- ---------------------- 5.5/12.8 MB 511.7 kB/s eta 0:00:15
     ---------------- ---------------------- 5.5/12.8 MB 511.7 kB/s eta 0:00:15
     ----------------- --------------------- 5.8/12.8 MB 511.0 kB/s eta 0:00:14
     ----------------- --------------------- 5.8/12.8 MB 511.0 kB/s eta 0:00:14
     ------------------ -------------------- 6.0/12.8 MB 506.9 kB/s eta 0:00:14
     ------------------ -------------------- 6.0/12.8 MB 506.9 kB/s eta 0:00:14
     ------------------ -------------------- 6.0/12.8 MB 506.9 kB/s eta 0:00:14
     ------------------ -------------------- 6.0/12.8 MB 506.9 kB/s eta 0:00:14
     ------------------- ------------------- 6.3/12.8 MB 499.8 kB/s eta 0:00:14
     ------------------- ------------------- 6.3/12.8 MB 499.8 kB/s eta 0:00:14
     ------------------- ------------------- 6.3/12.8 MB 499.8 kB/s eta 0:00:14
     ------------------- ------------------- 6.3/12.8 MB 499.8 kB/s eta 0:00:14
     ------------------- ------------------- 6.6/12.8 MB 488.0 kB/s eta 0:00:13
     ------------------- ------------------- 6.6/12.8 MB 488.0 kB/s eta 0:00:13
     ------------------- ------------------- 6.6/12.8 MB 488.0 kB/s eta 0:00:13
     ------------------- ------------------- 6.6/12.8 MB 488.0 kB/s eta 0:00:13
     ------------------- ------------------- 6.6/12.8 MB 488.0 kB/s eta 0:00:13
     -------------------- ------------------ 6.8/12.8 MB 468.2 kB/s eta 0:00:13
     -------------------- ------------------ 6.8/12.8 MB 468.2 kB/s eta 0:00:13
     -------------------- ------------------ 6.8/12.8 MB 468.2 kB/s eta 0:00:13
     -------------------- ------------------ 6.8/12.8 MB 468.2 kB/s eta 0:00:13
     --------------------- ----------------- 7.1/12.8 MB 458.1 kB/s eta 0:00:13
     --------------------- ----------------- 7.1/12.8 MB 458.1 kB/s eta 0:00:13
     --------------------- ----------------- 7.1/12.8 MB 458.1 kB/s eta 0:00:13
     --------------------- ----------------- 7.1/12.8 MB 458.1 kB/s eta 0:00:13
     --------------------- ----------------- 7.1/12.8 MB 458.1 kB/s eta 0:00:13
     ---------------------- ---------------- 7.3/12.8 MB 444.2 kB/s eta 0:00:13
     ---------------------- ---------------- 7.3/12.8 MB 444.2 kB/s eta 0:00:13
     ---------------------- ---------------- 7.3/12.8 MB 444.2 kB/s eta 0:00:13
     ---------------------- ---------------- 7.3/12.8 MB 444.2 kB/s eta 0:00:13
     ---------------------- ---------------- 7.3/12.8 MB 444.2 kB/s eta 0:00:13
     ---------------------- ---------------- 7.3/12.8 MB 444.2 kB/s eta 0:00:13
     ----------------------- --------------- 7.6/12.8 MB 425.8 kB/s eta 0:00:13
     ----------------------- --------------- 7.6/12.8 MB 425.8 kB/s eta 0:00:13
     ----------------------- --------------- 7.6/12.8 MB 425.8 kB/s eta 0:00:13
     ----------------------- --------------- 7.6/12.8 MB 425.8 kB/s eta 0:00:13
     ----------------------- --------------- 7.9/12.8 MB 422.1 kB/s eta 0:00:12
     ----------------------- --------------- 7.9/12.8 MB 422.1 kB/s eta 0:00:12
     ----------------------- --------------- 7.9/12.8 MB 422.1 kB/s eta 0:00:12
     ------------------------ -------------- 8.1/12.8 MB 423.5 kB/s eta 0:00:12
     ------------------------ -------------- 8.1/12.8 MB 423.5 kB/s eta 0:00:12
     ------------------------- ------------- 8.4/12.8 MB 425.7 kB/s eta 0:00:11
     ------------------------- ------------- 8.4/12.8 MB 425.7 kB/s eta 0:00:11
     ------------------------- ------------- 8.4/12.8 MB 425.7 kB/s eta 0:00:11
     -------------------------- ------------ 8.7/12.8 MB 427.6 kB/s eta 0:00:10
     -------------------------- ------------ 8.7/12.8 MB 427.6 kB/s eta 0:00:10
     -------------------------- ------------ 8.7/12.8 MB 427.6 kB/s eta 0:00:10
     --------------------------- ----------- 8.9/12.8 MB 426.2 kB/s eta 0:00:10
     --------------------------- ----------- 8.9/12.8 MB 426.2 kB/s eta 0:00:10
     --------------------------- ----------- 9.2/12.8 MB 427.1 kB/s eta 0:00:09
     --------------------------- ----------- 9.2/12.8 MB 427.1 kB/s eta 0:00:09
     --------------------------- ----------- 9.2/12.8 MB 427.1 kB/s eta 0:00:09
     ---------------------------- ---------- 9.4/12.8 MB 429.4 kB/s eta 0:00:08
     ---------------------------- ---------- 9.4/12.8 MB 429.4 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 431.1 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 431.1 kB/s eta 0:00:08
     ----------------------------- --------- 9.7/12.8 MB 431.1 kB/s eta 0:00:08
     ----------------------------- -------- 10.0/12.8 MB 434.0 kB/s eta 0:00:07
     ------------------------------ ------- 10.2/12.8 MB 437.9 kB/s eta 0:00:06
     ------------------------------ ------- 10.2/12.8 MB 437.9 kB/s eta 0:00:06
     ------------------------------ ------- 10.2/12.8 MB 437.9 kB/s eta 0:00:06
     ------------------------------- ------ 10.5/12.8 MB 438.6 kB/s eta 0:00:06
     ------------------------------- ------ 10.5/12.8 MB 438.6 kB/s eta 0:00:06
     ------------------------------- ------ 10.5/12.8 MB 438.6 kB/s eta 0:00:06
     ------------------------------- ------ 10.7/12.8 MB 440.0 kB/s eta 0:00:05
     ------------------------------- ------ 10.7/12.8 MB 440.0 kB/s eta 0:00:05
     ------------------------------- ------ 10.7/12.8 MB 440.0 kB/s eta 0:00:05
     -------------------------------- ----- 11.0/12.8 MB 439.4 kB/s eta 0:00:05
     -------------------------------- ----- 11.0/12.8 MB 439.4 kB/s eta 0:00:05
     -------------------------------- ----- 11.0/12.8 MB 439.4 kB/s eta 0:00:05
     -------------------------------- ----- 11.0/12.8 MB 439.4 kB/s eta 0:00:05
     -------------------------------- ----- 11.0/12.8 MB 439.4 kB/s eta 0:00:05
     -------------------------------- ----- 11.0/12.8 MB 439.4 kB/s eta 0:00:05
     -------------------------------- ----- 11.0/12.8 MB 439.4 kB/s eta 0:00:05
     -------------------------------- ----- 11.0/12.8 MB 439.4 kB/s eta 0:00:05
     -------------------------------- ----- 11.0/12.8 MB 439.4 kB/s eta 0:00:05
     -------------------------------- ----- 11.0/12.8 MB 439.4 kB/s eta 0:00:05
     -------------------------------- ----- 11.0/12.8 MB 439.4 kB/s eta 0:00:05
     -------------------------------- ----- 11.0/12.8 MB 439.4 kB/s eta 0:00:05
     --------------------------------- ---- 11.3/12.8 MB 405.0 kB/s eta 0:00:04
     --------------------------------- ---- 11.3/12.8 MB 405.0 kB/s eta 0:00:04
     --------------------------------- ---- 11.3/12.8 MB 405.0 kB/s eta 0:00:04
     --------------------------------- ---- 11.3/12.8 MB 405.0 kB/s eta 0:00:04
     --------------------------------- ---- 11.3/12.8 MB 405.0 kB/s eta 0:00:04
     ---------------------------------- --- 11.5/12.8 MB 400.5 kB/s eta 0:00:04
     ---------------------------------- --- 11.5/12.8 MB 400.5 kB/s eta 0:00:04
     ---------------------------------- --- 11.5/12.8 MB 400.5 kB/s eta 0:00:04
     ---------------------------------- --- 11.5/12.8 MB 400.5 kB/s eta 0:00:04
     ---------------------------------- --- 11.5/12.8 MB 400.5 kB/s eta 0:00:04
     ---------------------------------- --- 11.5/12.8 MB 400.5 kB/s eta 0:00:04
     ---------------------------------- --- 11.5/12.8 MB 400.5 kB/s eta 0:00:04
     ---------------------------------- --- 11.5/12.8 MB 400.5 kB/s eta 0:00:04
     ----------------------------------- -- 11.8/12.8 MB 386.8 kB/s eta 0:00:03
     ----------------------------------- -- 11.8/12.8 MB 386.8 kB/s eta 0:00:03
     ----------------------------------- -- 11.8/12.8 MB 386.8 kB/s eta 0:00:03
     ----------------------------------- -- 11.8/12.8 MB 386.8 kB/s eta 0:00:03
     ----------------------------------- -- 11.8/12.8 MB 386.8 kB/s eta 0:00:03
     ----------------------------------- -- 11.8/12.8 MB 386.8 kB/s eta 0:00:03
     ----------------------------------- -- 11.8/12.8 MB 386.8 kB/s eta 0:00:03
     ----------------------------------- -- 11.8/12.8 MB 386.8 kB/s eta 0:00:03
     ----------------------------------- -- 11.8/12.8 MB 386.8 kB/s eta 0:00:03
     ----------------------------------- -- 11.8/12.8 MB 386.8 kB/s eta 0:00:03
     ----------------------------------- -- 11.8/12.8 MB 386.8 kB/s eta 0:00:03
     ----------------------------------- -- 11.8/12.8 MB 386.8 kB/s eta 0:00:03
     ----------------------------------- -- 11.8/12.8 MB 386.8 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 334.5 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 334.5 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 334.5 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 334.5 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 334.5 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 334.5 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 334.5 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 334.5 kB/s eta 0:00:03
     ------------------------------------ - 12.3/12.8 MB 308.4 kB/s eta 0:00:02
     ------------------------------------ - 12.3/12.8 MB 308.4 kB/s eta 0:00:02
     ------------------------------------ - 12.3/12.8 MB 308.4 kB/s eta 0:00:02
     ------------------------------------ - 12.3/12.8 MB 308.4 kB/s eta 0:00:02
     ------------------------------------ - 12.3/12.8 MB 308.4 kB/s eta 0:00:02
     ------------------------------------ - 12.3/12.8 MB 308.4 kB/s eta 0:00:02
     -------------------------------------  12.6/12.8 MB 292.0 kB/s eta 0:00:01
     -------------------------------------  12.6/12.8 MB 292.0 kB/s eta 0:00:01
     -------------------------------------  12.6/12.8 MB 292.0 kB/s eta 0:00:01
     -------------------------------------  12.6/12.8 MB 292.0 kB/s eta 0:00:01
     -------------------------------------- 12.8/12.8 MB 288.9 kB/s eta 0:00:00
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [21]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [22]:
import string

punctuations = list(string.punctuation) # Get all punctuation : !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [23]:
import pandas as pd

fake_df = pd.read_csv(r'C:\Users\pc\Downloads\Fake.csv')
true_df = pd.read_csv(r'C:\Users\pc\Downloads\True.csv')

In [24]:
fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [25]:
true_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [26]:
fake_df['label'] = 0
true_df['label'] = 1

In [27]:
true_df_cols = true_df.columns
fake_df_cols = fake_df.columns

print (true_df_cols)
print (fake_df_cols)

Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')
Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')

In [28]:
data = pd.concat([fake_df, true_df], ignore_index=True)
data = data.sample(frac=1, random_state=42).reset_index(drop=True) #shuffle the dataset

data.head()

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

In [29]:
X = data['text'].tolist()[:50]
y = data['label'].tolist()[:50]
print(X[0])
print("--------------------------------------------------------------------------------------------")
print(X[40])

21st Century Wire says Ben Stein, reputable professor from, Pepperdine University (also of some Hollywood fame appearing in TV shows and films such as Ferris Bueller s Day Off) made some provocative statements on Judge Jeanine Pirro s show recently. While discussing the halt that was imposed on President Trump s Executive Order on travel. Stein referred to the judgement by the 9th Circuit Court in Washington state as a  Coup d tat against the executive branch and against the constitution.  Stein went on to call the Judges in Seattle  political puppets  and the judiciary  political pawns. Watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any Presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the Executive Order.READ MORE TRUMP NEWS AT: 21st Century Wire Trump FilesSUPPORT OUR WORK BY SUBSCRIBING & BECOMING A MEMBER @21WIRE.TV
--------------------------------------------------------------------------------------------
(Reuters) - Georgia Governor Nathan Deal issued a mandatory evacuation order on Thursday for the state s coast, including historic Savannah, as deadly Hurricane Irma rolled toward Florida and the southeastern United States. The evacuation order for areas east of Interstate 95 and some areas to its west takes effect Saturday at 8 a.m., Deal said in a statement. The governor also authorized up to 5,000 Georgia National Guard members to respond to the storm and expanded a state of emergency to 30 southeast Georgia counties. The order affects the cities of Savannah and Brunswick in Georgia, which has not been hit by a Category 3 hurricane or higher since 1898, according to WSB-TV.  I encourage all Georgians in our coastal areas that could be impacted by this storm to evacuate the area as soon as possible,  Deal said in a statement. Irma, one of the most powerful Atlantic storms in a century, plowed past the Dominican Republic toward Haiti on Thursday after devastating a string of Caribbean islands and killing at least 10 people. Irma will likely hit Florida as a powerful Category 4 storm on Sunday, with storm surges and flooding beginning within the next 48 hours, according to the NHC. Gas shortages in the  Miami-Fort Lauderdale area worsened on Thursday, with sales up to five times the norm. The storm s exact path is uncertain, but it could affect Georgia and the Carolinas early next week.

![ ](https://img.shields.io/badge/Text_normalization-red)

In [30]:
!pip install num2words

Requirement already satisfied: num2words in c:\users\pc\anaconda3\lib\site-packages (0.5.14)
Requirement already satisfied: docopt>=0.6.2 in c:\users\pc\anaconda3\lib\site-packages (from num2words) (0.6.2)

![ ](https://img.shields.io/badge/Number_to_words_conversion%20%20-blue)

In [31]:
from num2words import num2words
import re
X2=[re.sub(r'\b(\d+)(st|nd|rd|th)\b', lambda m: num2words(int(m.group(1)), to='ordinal'), text) for text in X]#goup(1) je prends seulement les chiffres
X2 = [re.sub(r'\b\d+\b', lambda m: num2words(int(m.group())), text) for text in X2]
print(X2[0])
print("-----------------------------------------------------------------------------------")
print(X2[40])

twenty-first Century Wire says Ben Stein, reputable professor from, Pepperdine University (also of some Hollywood fame appearing in TV shows and films such as Ferris Bueller s Day Off) made some provocative statements on Judge Jeanine Pirro s show recently. While discussing the halt that was imposed on President Trump s Executive Order on travel. Stein referred to the judgement by the ninth Circuit Court in Washington state as a  Coup d tat against the executive branch and against the constitution.  Stein went on to call the Judges in Seattle  political puppets  and the judiciary  political pawns. Watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any Presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the Executive Order.READ MORE TRUMP NEWS AT: twenty-first Century Wire Trump FilesSUPPORT OUR WORK BY SUBSCRIBING & BECOMING A MEMBER @21WIRE.TV
-----------------------------------------------------------------------------------
(Reuters) - Georgia Governor Nathan Deal issued a mandatory evacuation order on Thursday for the state s coast, including historic Savannah, as deadly Hurricane Irma rolled toward Florida and the southeastern United States. The evacuation order for areas east of Interstate ninety-five and some areas to its west takes effect Saturday at eight a.m., Deal said in a statement. The governor also authorized up to five,zero Georgia National Guard members to respond to the storm and expanded a state of emergency to thirty southeast Georgia counties. The order affects the cities of Savannah and Brunswick in Georgia, which has not been hit by a Category three hurricane or higher since one thousand, eight hundred and ninety-eight, according to WSB-TV.  I encourage all Georgians in our coastal areas that could be impacted by this storm to evacuate the area as soon as possible,  Deal said in a statement. Irma, one of the most powerful Atlantic storms in a century, plowed past the Dominican Republic toward Haiti on Thursday after devastating a string of Caribbean islands and killing at least ten people. Irma will likely hit Florida as a powerful Category four storm on Sunday, with storm surges and flooding beginning within the next forty-eight hours, according to the NHC. Gas shortages in the  Miami-Fort Lauderdale area worsened on Thursday, with sales up to five times the norm. The storm s exact path is uncertain, but it could affect Georgia and the Carolinas early next week.

![ ](https://img.shields.io/badge/drop_stop_words%20%20-blue)

In [32]:
X3 = []
for text in X2:
    text_sp = nlp(text)
    tokens = [t for t in text_sp if not t.is_stop]
    X3.append(tokens)
print (X3[0])

[-, Century, Wire, says, Ben, Stein, ,, reputable, professor, ,, Pepperdine, University, (, Hollywood, fame, appearing, TV, shows, films, Ferris, Bueller, s, Day, ), provocative, statements, Judge, Jeanine, Pirro, s, recently, ., discussing, halt, imposed, President, Trump, s, Executive, Order, travel, ., Stein, referred, judgement, ninth, Circuit, Court, Washington, state,  , Coup, d, tat, executive, branch, constitution, .,  , Stein, went, Judges, Seattle,  , political, puppets,  , judiciary,  , political, pawns, ., Watch, interview, complete, statements, note, stark, contrast, rhetoric, leftist, media, pundits, neglect, note, court, blocked, Presidential, orders, immigration, past, discuss, legal, efficacy, halt, actual, text, Executive, Order, ., READ, TRUMP, NEWS, :, -, Century, Wire, Trump, FilesSUPPORT, WORK, SUBSCRIBING, &, MEMBER, @21WIRE.TV]

![ ](https://img.shields.io/badge/drop_punctuations%20%20-blue)

In [33]:
X4 = []
for text in X3:
    tokens = []
    for token in text:
        if token.text not in punctuations :
            tokens.append(token.text)#.text!
    X4.append(tokens)
print(X4[0])

['Century', 'Wire', 'says', 'Ben', 'Stein', 'reputable', 'professor', 'Pepperdine', 'University', 'Hollywood', 'fame', 'appearing', 'TV', 'shows', 'films', 'Ferris', 'Bueller', 's', 'Day', 'provocative', 'statements', 'Judge', 'Jeanine', 'Pirro', 's', 'recently', 'discussing', 'halt', 'imposed', 'President', 'Trump', 's', 'Executive', 'Order', 'travel', 'Stein', 'referred', 'judgement', 'ninth', 'Circuit', 'Court', 'Washington', 'state', ' ', 'Coup', 'd', 'tat', 'executive', 'branch', 'constitution', ' ', 'Stein', 'went', 'Judges', 'Seattle', ' ', 'political', 'puppets', ' ', 'judiciary', ' ', 'political', 'pawns', 'Watch', 'interview', 'complete', 'statements', 'note', 'stark', 'contrast', 'rhetoric', 'leftist', 'media', 'pundits', 'neglect', 'note', 'court', 'blocked', 'Presidential', 'orders', 'immigration', 'past', 'discuss', 'legal', 'efficacy', 'halt', 'actual', 'text', 'Executive', 'Order', 'READ', 'TRUMP', 'NEWS', 'Century', 'Wire', 'Trump', 'FilesSUPPORT', 'WORK', 'SUBSCRIBING', 'MEMBER', '@21WIRE.TV']

![ ](https://img.shields.io/badge/Process%20%20-orange)

In [48]:
X_process = []
for text in X4:
    text_pro = nlp(' '.join(text))
    lemmas = []
    for token in text_pro:
        lemmas.append(token.lemma_)
    X_process.append(lemmas)

print(X_process[0])

['Century', 'Wire', 'say', 'Ben', 'Stein', 'reputable', 'professor', 'Pepperdine', 'University', 'Hollywood', 'fame', 'appear', 'tv', 'show', 'film', 'Ferris', 'Bueller', 's', 'Day', 'provocative', 'statement', 'Judge', 'Jeanine', 'Pirro', 's', 'recently', 'discuss', 'halt', 'impose', 'President', 'Trump', 's', 'Executive', 'Order', 'travel', 'Stein', 'refer', 'judgement', 'ninth', 'Circuit', 'Court', 'Washington', 'state', '  ', 'Coup', 'd', 'tat', 'executive', 'branch', 'constitution', '  ', 'Stein', 'go', 'Judges', 'Seattle', '  ', 'political', 'puppet', '  ', 'judiciary', '  ', 'political', 'pawn', 'watch', 'interview', 'complete', 'statement', 'note', 'stark', 'contrast', 'rhetoric', 'leftist', 'medium', 'pundit', 'neglect', 'note', 'court', 'block', 'presidential', 'order', 'immigration', 'past', 'discuss', 'legal', 'efficacy', 'halt', 'actual', 'text', 'Executive', 'Order', 'READ', 'TRUMP', 'NEWS', 'Century', 'Wire', 'Trump', 'filessupport', 'work', 'subscribe', 'member', '@21wire.tv']

![ ](https://img.shields.io/badge/Vocabs%20%20-blue)

In [58]:
vocabs = set()
for liste in X_process:
    for word in liste:
        vocabs.add(word)  
#vocabs = list(vocabs) 
#vocabs.sort()

Vectors = []

for i in X_process:
    vec = []
    
    for word in vocabs:
        vec.append(i.count(word))
    
    Vectors.append(vec)

#print(vocabs)
print(Vectors[0])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

## BOW
>1-gram BOW

[![Naive Bayes](https://img.shields.io/badge/Naive_Bayes-classification-pink)](https://digitalpro.dev)

> Convert X docs to NumPy array

In [59]:
import numpy as np

X_vectors = np.array(Vectors) #define your Vectors
y_array = np.array(y)

> Split into train/test

In [60]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_vectors, y_array, test_size=0.2, random_state=42, stratify=y_array
)

> Train Naive Bayes classifier

In [61]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score, classification_report

nb = BernoulliNB()
nb.fit(X_train, y_train)    # Train

y_pred = nb.predict(X_test) # Predict

> Evaluate

In [62]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7
              precision    recall  f1-score   support

           0       0.75      0.60      0.67         5
           1       0.67      0.80      0.73         5

    accuracy                           0.70        10
   macro avg       0.71      0.70      0.70        10
weighted avg       0.71      0.70      0.70        10